-- =============================================
-- 出院申请表
-- 对应功能: M02-05 出院管理
-- 创建日期: 2026-06-18
-- =============================================

-- 出院申请表
CREATE TABLE IF NOT EXISTS `his_discharge_apply` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '出院申请ID',
    `apply_no` VARCHAR(30) NOT NULL COMMENT '申请单号',
    `admission_id` BIGINT NOT NULL COMMENT '入院记录ID',
    `admission_no` VARCHAR(30) NOT NULL COMMENT '住院号',
    `patient_id` BIGINT NOT NULL COMMENT '患者ID',
    `patient_name` VARCHAR(50) NOT NULL COMMENT '患者姓名',
    `gender` CHAR(1) COMMENT '性别',
    `age` INT COMMENT '年龄',
    `dept_id` BIGINT NOT NULL COMMENT '科室ID',
    `dept_name` VARCHAR(100) NOT NULL COMMENT '科室名称',
    `ward_id` BIGINT COMMENT '病区ID',
    `ward_name` VARCHAR(100) COMMENT '病区名称',
    `bed_id` BIGINT COMMENT '床位ID',
    `bed_no` VARCHAR(20) COMMENT '床位号',
    `attending_doctor_id` BIGINT COMMENT '主治医生ID',
    `attending_doctor_name` VARCHAR(50) COMMENT '主治医生姓名',
    `admission_date` DATETIME NOT NULL COMMENT '入院日期',
    `admission_diagnosis` VARCHAR(500) COMMENT '入院诊断',
    `admission_diagnosis_code` VARCHAR(50) COMMENT '入院诊断编码(ICD-10)',
    `discharge_date` DATETIME NOT NULL COMMENT '拟定出院日期',
    `discharge_way` TINYINT NOT NULL COMMENT '出院方式: 1医嘱出院/2自动出院/3转院/4死亡',
    `discharge_diagnosis` VARCHAR(500) COMMENT '出院诊断',
    `discharge_diagnosis_code` VARCHAR(50) COMMENT '出院诊断编码(ICD-10)',
    `discharge_diagnosis_remark` VARCHAR(500) COMMENT '出院诊断备注',
    `treatment_result` TINYINT COMMENT '治疗结果: 1治愈/2好转/3未愈/4死亡/5其他',
    `transfer_hospital` VARCHAR(100) COMMENT '转院医院(转院时填写)',
    `transfer_reason` VARCHAR(500) COMMENT '转院原因',
    `death_reason` VARCHAR(500) COMMENT '死亡原因(死亡时填写)',
    `death_time` DATETIME COMMENT '死亡时间',
    `apply_doctor_id` BIGINT NOT NULL COMMENT '申请医生ID',
    `apply_doctor_name` VARCHAR(50) NOT NULL COMMENT '申请医生姓名',
    `apply_time` DATETIME NOT NULL COMMENT '申请时间',
    `apply_reason` VARCHAR(500) COMMENT '申请原因',
    `status` TINYINT NOT NULL DEFAULT 1 COMMENT '状态: 1待审批/2已审批/3已驳回/4已出院/5已取消',
    `audit_doctor_id` BIGINT COMMENT '审批医生ID',
    `audit_doctor_name` VARCHAR(50) COMMENT '审批医生姓名',
    `audit_time` DATETIME COMMENT '审批时间',
    `audit_remark` VARCHAR(500) COMMENT '审批意见',
    `reject_reason` VARCHAR(500) COMMENT '驳回原因',
    `cancel_reason` VARCHAR(500) COMMENT '取消原因',
    `cancel_time` DATETIME COMMENT '取消时间',
    `order_stopped` TINYINT DEFAULT 0 COMMENT '是否停止医嘱: 0否/1是',
    `order_stop_time` DATETIME COMMENT '医嘱停止时间',
    `fee_settled` TINYINT DEFAULT 0 COMMENT '是否费用结算: 0否/1是',
    `fee_settle_time` DATETIME COMMENT '费用结算时间',
    `remark` VARCHAR(500) COMMENT '备注',
    `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_apply_no` (`apply_no`),
    KEY `idx_discharge_admission` (`admission_id`),
    KEY `idx_discharge_patient` (`patient_id`),
    KEY `idx_discharge_dept` (`dept_id`),
    KEY `idx_discharge_status` (`status`),
    KEY `idx_discharge_date` (`discharge_date`),
    KEY `idx_discharge_apply_time` (`apply_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='出院申请表';
